### ISSUE TITLE
Spring in Action

### ISSUE THREAD

**Issue by wyiyi** [oopstorm/oopstorm.github.io#27]
此书主要介绍了**Spring in Action3.0**的版本。
Spring 3.0引入了SPEL、Spring 表达式语言、ioc容器注入的注解以及用户对rest的支持。本书介绍了Spring 3.0重要的几个方面：REST、远程服务、消息、安全、MVC、web Flow等。

**Spring in Action分为三部分，第一部分介绍Spring框架的核心知识**（使用AOP和DI 将Spring 促进java代码的松耦合、装配Bean、利用注解方式减少xml配置、面向切面的Spring）。**第二部分在第一部分的基础上进行深入介绍Spring程序常用的元素**（数据库、事务管理、使用MVC构建WEB应用程序、使用Spring web Flow和保护Spring应用）。**第三部分展示的Spring 与其他应用和服务怎样进行集成**（远程服务、为Spring添加REST功能、消息发送和接收异步消息、使用JMX管理Spring Bean以及调度、发送邮件和访问JNDI配置资源）。

**Comment by AlphaHinex** [comment]
https://github.com/oopstorm/bookworms/blob/master/CONTRIBUTING.md
