### ISSUE TITLE
在你身边，为你设计

### ISSUE THREAD

**Issue by feel1884257** [oopstorm/oopstorm.github.io#28]
一切以用户价值为依托
1.沉浸其中进行产品设计，深入了解用户的心理和感受后再进行相应的设计-多了解感性信息 罗伯特.卡帕 Robert Capa:如果你的照片拍的不够好，那是因为你靠的不够近。
2.硬数据和软数据同样重要，硬数据决定产品的战略层，软数据决定产品设计的细节。
3.要逐步形成用户取样模型的样本库，通过用户模型的样本库我们可以进行更快捷有效的产品设计。
4.UE用户体验是一个产品设计理念，贯穿整个产品设计流程，所有产品的参与者都应以用户体验为主导思想进行产品的UCD流程的开展。

**Comment by AlphaHinex** [comment]
https://github.com/oopstorm/bookworms/blob/master/CONTRIBUTING.md#0x10
按这个方式提吧

**Comment by feel1884257** [comment]
OK
