### ISSUE TITLE
about face 4.0:交互设计精髓 · OopStorm

### ISSUE THREAD

**Issue by feel1884257** [oopstorm/oopstorm.github.io#50]
图书简介：

交互设计师之父--Alan Cooper的经典著作，一本定义产品设计师职业范畴及如何在各类产品团队中发挥作用的设计师工具书。

分享内容：

1.交互设计的强大力量不容置疑：它能够让用户在工作、娱乐和交流之际，获得难忘、有效、简单，以及有益的体验。
2.交互设计本身就是一项人文事业。与产品和服务互动的是人，交互设计的首要目标是满足 人的需求和欲望。理解这些目标和需求的最佳方式是把它们当成故事——逻辑和情感随时间而 演变。要回应用户的这些故事，数字产品必须表达自身的行为故事，不仅要在逻辑、数据条目 和展示层次做出恰当的回应，还要在更加人性化的层面有所响应。
3.在敏捷开发团队中，设计师要定义用户体验在产品中的体现，在敏捷设计中，设计师必须分清重点、形成思维图像；他们可以让期待结果变得清晰具体, 还可以围绕必须对何种元素进行开发从而实现期待结果这一话题进行对话。
4.没有企业文化支持交互设计及其目标，世界上的任何设计技术和流程都难以成功。苹果公 司（Apple)成为用户体验的典范，不是因为苹果员工的设计技术高超，而是因为苹果的前任领 导史蒂夫•乔布斯（Steve Jobs)不遗余力地拥护设计的力量。

**Comment by AlphaHinex** [comment]
@feel1884257 写在 https://github.com/oopstorm/oopstorm.github.io/issues/51 里
